import { Geist, Geist_Mono, Metal } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Eater } from "next/font/google";
import { Metal_Mania } from "@next/font/google";
import { Creepster } from "next/font/google";
import { Zain } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const eater = Eater({
  weight: "400",
  subsets: ["latin"],
});

export const metalMania = Metal_Mania({
  weight: "400",
  subsets: ["latin"],
});

export const creepster = Creepster({
  weight: "400",
  subsets: ["latin"],
});

export const zain = Zain({
  weight: "400",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${zain.className} text-2xl antialiased`}>
        <Header />
        <main className="max-w-6xl mx-auto px-4 text-center pt-5">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
